# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-ssm-tls-self-signed-cert
  description: This module creates a self-signed certificate and writes it alongside with its key to SSM Parameter Store (or alternatively AWS Secrets Manager).
  homepage: https://cloudposse.com/accelerate
  topics: terraform, hcl2, aws, terraform-modules, ssm, certificate, certificate-signing-request
